### ISSUE TITLE
splitter get the wrong name in the workflow 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#101]
The dependency name is 'splitter_843c230' while the task name is 'splitter-843c230'
 Internal Server Error: templates.workflow-test sorting failed: invalid dependency splitter.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-test-
spec:
    entrypoint: workflow-test
    arguments:
      parameters:
      - name: param_login
        value: ''
      - name: param_password
        value: ''
      - name: param_hostname
        value: ''
    templates:
    - name: workflow-test
      dag:
        tasks:
        - name: fetch-laz-files-01-04-22
          template: fetch-laz-files-01-04-22-tmp
          arguments:
            parameters:
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
        - name: retiling-01-04-22
          dependencies: [ splitter_843c230 ]
          template: retiling-01-04-22-tmp
          arguments:
            parameters:
            - {name: splitter_target, value: "{{item}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
          withParam: "{{tasks.splitter_843c230.outputs.parameters.splitter_target}}"
        - name: splitter-843c230
          dependencies: [ fetch-laz-files-01-04-22 ]
          template: splitter-843c230-tmp
          arguments:
            parameters:
            - {name: laz_files, value: "{{tasks.fetch-laz-files-01-04-22.outputs.parameters.laz_files}}"}
        - name: feature-extraction-01-04-22
          dependencies: [ retiling-01-04-22 ]
          template: feature-extraction-01-04-22-tmp
          arguments:
            parameters:
            - {name: remote_path_retiled, value: "{{tasks.retiling-01-04-22.outputs.parameters.remote_path_retiled}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
        - name: geotiff-export-01-04-22
          dependencies: [ splitter_a800753 ]
          template: geotiff-export-01-04-22-tmp
          arguments:
            parameters:
            - {name: splitter_target, value: "{{item}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
          withParam: "{{tasks.splitter_a800753.outputs.parameters.splitter_target}}"
        - name: splitter-a800753
          dependencies: [ feature-extraction-01-04-22 ]
          template: splitter-a800753-tmp
          arguments:
            parameters:
            - {name: features, value: "{{tasks.feature-extraction-01-04-22.outputs.parameters.features}}"}

    - name: fetch-laz-files-01-04-22-tmp
      outputs:
        parameters:
          - name: laz_files
            valueFrom:
              path: /tmp/laz_files.json
      container:
        image: "qcdis/fetch-laz-files-01-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python fetch-laz-files-01-04-22.py
            --param_login {{workflow.parameters.param_login}}
            --param_hostname {{workflow.parameters.param_hostname}}
            --param_password {{workflow.parameters.param_password}};
    - name: retiling-01-04-22-tmp
      inputs:
        parameters:
        - name: splitter_target
        - name: param_login
        - name: param_password
        - name: param_hostname
      outputs:
        parameters:
          - name: remote_path_retiled
            valueFrom:
              path: /tmp/remote_path_retiled.json
      container:
        image: "qcdis/retiling-01-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python retiling-01-04-22.py
            --splitter_target {{inputs.parameters.splitter_target}}
            --param_login {{workflow.parameters.param_login}}
            --param_password {{workflow.parameters.param_password}}
            --param_hostname {{workflow.parameters.param_hostname}};
    - name: splitter-843c230-tmp
      inputs:
        parameters:
        - name: laz_files
      outputs:
        parameters:
          - name: splitter_target
            valueFrom:
              path: /tmp/splitter_target.json
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo splitter-843c230"]
    - name: feature-extraction-01-04-22-tmp
      inputs:
        parameters:
        - name: remote_path_retiled
        - name: param_login
        - name: param_password
        - name: param_hostname
      outputs:
        parameters:
          - name: features
            valueFrom:
              path: /tmp/features.json
      container:
        image: "qcdis/feature-extraction-01-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python feature-extraction-01-04-22.py
            --remote_path_retiled {{inputs.parameters.remote_path_retiled}}
            --param_login {{workflow.parameters.param_login}}
            --param_password {{workflow.parameters.param_password}}
            --param_hostname {{workflow.parameters.param_hostname}};
    - name: geotiff-export-01-04-22-tmp
      inputs:
        parameters:
        - name: splitter_target
        - name: param_login
        - name: param_password
        - name: param_hostname
      outputs:
        parameters:
      container:
        image: "qcdis/geotiff-export-01-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python geotiff-export-01-04-22.py
            --splitter_target {{inputs.parameters.splitter_target}}
            --param_login {{workflow.parameters.param_login}}
            --param_password {{workflow.parameters.param_password}}
            --param_hostname {{workflow.parameters.param_hostname}};
    - name: splitter-a800753-tmp
      inputs:
        parameters:
        - name: features
      outputs:
        parameters:
          - name: splitter_target
            valueFrom:
              path: /tmp/splitter_target.json
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo splitter-a800753"]
```
