### ISSUE TITLE
 Internal Server Error: templates.workflow-test.tasks.geotiff-export-08-04-22-a8b9453 template name 'geotiff-export-08-04-22-a8b9453-tmp' undefined

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#115]
Generating WF from:

![Screenshot 2022-04-23 21:07:09](https://user-images.githubusercontent.com/9680609/164942899-e9a7b66d-0554-4708-8cd3-3e5d79a26a16.png)

Throws :  Internal Server Error: templates.workflow-test.tasks.geotiff-export-08-04-22-a8b9453 template name 'geotiff-export-08-04-22-a8b9453-tmp' **undefined**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-test-
spec:
    entrypoint: workflow-test
    arguments:
      parameters:
      - name: param_feature_name
        value: ''
      - name: param_hostname
        value: ''
      - name: param_attribute
        value: ''
      - name: param_n_tiles_side
        value: ''
      - name: param_filter_type
        value: ''
      - name: param_min_y
        value: ''
      - name: param_apply_filter_value
        value: ''
      - name: param_min_x
        value: ''
      - name: param_validate_precision
        value: ''
      - name: param_max_y
        value: ''
      - name: param_tile_mesh_size
        value: ''
      - name: param_password
        value: ''
      - name: param_login
        value: ''
      - name: param_max_x
        value: ''
    templates:
    - name: workflow-test
      dag:
        tasks:
        - name: fetch-laz-files-08-04-22-5ec9a55
          template: fetch-laz-files-08-04-22-5ec9a55-tmp
          arguments:
            parameters:
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
        - name: splitter-e153472
          dependencies: [ fetch-laz-files-08-04-22-5ec9a55,  retiling-08-04-22-afd4ebe ]
          template: splitter-e153472-tmp
          arguments:
            parameters:
            - {name: laz_files_1799aeb, value: "{{tasks.fetch-laz-files-08-04-22-5ec9a55.outputs.parameters.laz_files_1799aeb}}"}
            - {name: laz_files_6cbcb71, value: "{{tasks.retiling-08-04-22-afd4ebe.outputs.parameters.laz_files_6cbcb71}}"}
        - name: retiling-08-04-22-afd4ebe
          dependencies: [ fetch-tiles-08-04-22-aefaaea ]
          template: retiling-08-04-22-afd4ebe-tmp
          arguments:
            parameters:
            - {name: remote_path_retiled_188b81b, value: "{{tasks.fetch-tiles-08-04-22-aefaaea.outputs.parameters.remote_path_retiled_188b81b}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_n_tiles_side, value: "{{workflow.parameters.param_n_tiles_side}}"}
            - {name: param_min_y, value: "{{workflow.parameters.param_min_y}}"}
            - {name: param_min_x, value: "{{workflow.parameters.param_min_x}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_max_y, value: "{{workflow.parameters.param_max_y}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_max_x, value: "{{workflow.parameters.param_max_x}}"}
        - name: fetch-tiles-08-04-22-aefaaea
          dependencies: [ splitter-c4ce8ed ]
          template: fetch-tiles-08-04-22-aefaaea-tmp
          arguments:
            parameters:
            - {name: splitter_source_c4ce8ed, value: "{{item}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
          withParam: "{{tasks.splitter-c4ce8ed.outputs.parameters.splitter_source_c4ce8ed}}"
        - name: splitter-c4ce8ed
          template: splitter-c4ce8ed-tmp
        - name: feature-extraction-08-04-22-beb5605
          dependencies: [ splitter-c4ce8ed,  geotiff-export-08-04-22-a8b9453 ]
          template: feature-extraction-08-04-22-beb5605-tmp
          arguments:
            parameters:
            - {name: splitter_target_c4ce8ed, value: "{{item}}"}
            - {name: features_139abd3, value: "{{tasks.geotiff-export-08-04-22-a8b9453.outputs.parameters.features_139abd3}}"}
            - {name: param_feature_name, value: "{{workflow.parameters.param_feature_name}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_attribute, value: "{{workflow.parameters.param_attribute}}"}
            - {name: param_n_tiles_side, value: "{{workflow.parameters.param_n_tiles_side}}"}
            - {name: param_filter_type, value: "{{workflow.parameters.param_filter_type}}"}
            - {name: param_min_y, value: "{{workflow.parameters.param_min_y}}"}
            - {name: param_apply_filter_value, value: "{{workflow.parameters.param_apply_filter_value}}"}
            - {name: param_min_x, value: "{{workflow.parameters.param_min_x}}"}
            - {name: param_validate_precision, value: "{{workflow.parameters.param_validate_precision}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_tile_mesh_size, value: "{{workflow.parameters.param_tile_mesh_size}}"}
            - {name: param_max_y, value: "{{workflow.parameters.param_max_y}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_max_x, value: "{{workflow.parameters.param_max_x}}"}
          withParam: "{{tasks.splitter-c4ce8ed.outputs.parameters.splitter_target_c4ce8ed}}"
        - name: geotiff-export-08-04-22-a8b9453
          template: geotiff-export-08-04-22-a8b9453-tmp
          arguments:
            parameters:
            - {name: param_feature_name, value: "{{workflow.parameters.param_feature_name}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}

    - name: fetch-laz-files-08-04-22-5ec9a55-tmp
      outputs:
        parameters:
          - name: laz_files_1799aeb
            valueFrom:
              path: /tmp/laz_files_1799aeb.json
      container:
        image: "skoulouzis/fetch-laz-files-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python fetch-laz-files-08-04-22.py
            --param_hostname "{{workflow.parameters.param_hostname}}"
            --param_password "{{workflow.parameters.param_password}}"
            --param_login "{{workflow.parameters.param_login}}"
            --id "1799aeb";
    - name: splitter-e153472-tmp
      inputs:
        parameters:
        - name: laz_files_1799aeb
        - name: laz_files_6cbcb71
      outputs:
        parameters:
          - name: splitter_target_e153472
            valueFrom:
              path: /tmp/splitter_target_e153472.json
      script:
        image: python:alpine3.9
        command: [python]
        source: |
          import json
          laz_files_1799aeb = {{inputs.parameters.laz_files_1799aeb}}
          f_out = open("/tmp/splitter_target_e153472.json", "w")
          f_out.write(json.dumps(laz_files_1799aeb))
          f_out.close()
    - name: retiling-08-04-22-afd4ebe-tmp
      inputs:
        parameters:
        - name: remote_path_retiled_188b81b
        - name: param_hostname
        - name: param_n_tiles_side
        - name: param_min_y
        - name: param_min_x
        - name: param_password
        - name: param_max_y
        - name: param_login
        - name: param_max_x
      outputs:
        parameters:
          - name: remote_path_retiled_6cbcb71
            valueFrom:
              path: /tmp/remote_path_retiled_6cbcb71.json
      container:
        image: "skoulouzis/retiling-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python retiling-08-04-22.py
            --remote "{{inputs.parameters.remote_path_retiled_188b81b}}"
            --param_hostname "{{workflow.parameters.param_hostname}}"
            --param_n_tiles_side "{{workflow.parameters.param_n_tiles_side}}"
            --param_min_y "{{workflow.parameters.param_min_y}}"
            --param_min_x "{{workflow.parameters.param_min_x}}"
            --param_password "{{workflow.parameters.param_password}}"
            --param_max_y "{{workflow.parameters.param_max_y}}"
            --param_login "{{workflow.parameters.param_login}}"
            --param_max_x "{{workflow.parameters.param_max_x}}"
            --id "6cbcb71";
    - name: fetch-tiles-08-04-22-aefaaea-tmp
      inputs:
        parameters:
        - name: splitter_source_c4ce8ed
        - name: param_hostname
        - name: param_password
        - name: param_login
      outputs:
        parameters:
          - name: tiles_188b81b
            valueFrom:
              path: /tmp/tiles_188b81b.json
      container:
        image: "skoulouzis/fetch-tiles-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python fetch-tiles-08-04-22.py
            --tiles "{{inputs.parameters.splitter_source_c4ce8ed}}"
            --param_hostname "{{workflow.parameters.param_hostname}}"
            --param_password "{{workflow.parameters.param_password}}"
            --param_login "{{workflow.parameters.param_login}}"
            --id "188b81b";
    - name: splitter-c4ce8ed-tmp
      outputs:
        parameters:
          - name: splitter_target_c4ce8ed
            valueFrom:
              path: /tmp/splitter_target_c4ce8ed.json
      script:
        image: python:alpine3.9
        command: [python]
        source: |
          import json      
```
