### ISSUE TITLE
 Internal Server Error: templates.workflow-test.tasks.retiling-19-04-22-a4b7508 failed to resolve {{tasks.fetch-tiles-19-04-22-a98d029.outputs.parameters.remote_path_retiled_a08a42d}}

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#122]
![Screenshot 2022-04-27 13:21:12](https://user-images.githubusercontent.com/9680609/165507389-dbae0947-1268-4ec8-a1c7-ae26fd42a753.png)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-test-
spec:
    entrypoint: workflow-test
    arguments:
      parameters:
      - name: param_hostname
        value: ''
      - name: param_min_x
        value: ''
      - name: param_login
        value: ''
      - name: param_max_y
        value: ''
      - name: param_n_tiles_side
        value: ''
      - name: param_password
        value: ''
      - name: param_max_x
        value: ''
      - name: param_min_y
        value: ''
    templates:
    - name: workflow-test
      dag:
        tasks:
        - name: fetch-laz-files-19-04-22-b8b5083
          template: fetch-laz-files-19-04-22-b8b5083-tmp
          arguments:
            parameters:
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
        - name: retiling-19-04-22-a4b7508
          dependencies: [ splitter-3a67fba,  fetch-tiles-19-04-22-a98d029 ]
          template: retiling-19-04-22-a4b7508-tmp
          arguments:
            parameters:
            - {name: splitter_target_3a67fba, value: "{{item}}"}
            - {name: remote_path_retiled_a08a42d, value: "{{tasks.fetch-tiles-19-04-22-a98d029.outputs.parameters.remote_path_retiled_a08a42d}}"}
            - {name: param_min_y, value: "{{workflow.parameters.param_min_y}}"}
            - {name: param_max_y, value: "{{workflow.parameters.param_max_y}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_n_tiles_side, value: "{{workflow.parameters.param_n_tiles_side}}"}
            - {name: param_max_x, value: "{{workflow.parameters.param_max_x}}"}
            - {name: param_min_x, value: "{{workflow.parameters.param_min_x}}"}
          withParam: "{{tasks.splitter-3a67fba.outputs.parameters.splitter_target_3a67fba}}"
        - name: splitter-3a67fba
          dependencies: [ fetch-laz-files-19-04-22-b8b5083 ]
          template: splitter-3a67fba-tmp
          arguments:
            parameters:
            - {name: laz_files_c31a712, value: "{{tasks.fetch-laz-files-19-04-22-b8b5083.outputs.parameters.laz_files_c31a712}}"}
        - name: fetch-tiles-19-04-22-a98d029
          template: fetch-tiles-19-04-22-a98d029-tmp
          arguments:
            parameters:
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}

    - name: fetch-laz-files-19-04-22-b8b5083-tmp
      outputs:
        parameters:
          - name: laz_files_c31a712
            valueFrom:
              path: /tmp/laz_files_c31a712.json
      container:
        image: "skoulouz/fetch-laz-files-19-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python fetch-laz-files-19-04-22.py
            --param_hostname "{{workflow.parameters.param_hostname}}"
            --param_password "{{workflow.parameters.param_password}}"
            --param_login "{{workflow.parameters.param_login}}"
            --id "c31a712";
    - name: retiling-19-04-22-a4b7508-tmp
      inputs:
        parameters:
        - name: splitter_target_3a67fba
        - name: remote_path_retiled_a08a42d
        - name: param_min_y
        - name: param_max_y
        - name: param_login
        - name: param_hostname
        - name: param_password
        - name: param_n_tiles_side
        - name: param_max_x
        - name: param_min_x
      outputs:
        parameters:
          - name: remote_path_retiled_1f7a48f
            valueFrom:
              path: /tmp/remote_path_retiled_1f7a48f.json
      container:
        image: "skoulouz/retiling-19-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python retiling-19-04-22.py
            --laz "{{inputs.parameters.splitter_target_3a67fba}}"
            --remote "{{inputs.parameters.remote_path_retiled_a08a42d}}"
            --param_min_y "{{workflow.parameters.param_min_y}}"
            --param_max_y "{{workflow.parameters.param_max_y}}"
            --param_login "{{workflow.parameters.param_login}}"
            --param_hostname "{{workflow.parameters.param_hostname}}"
            --param_password "{{workflow.parameters.param_password}}"
            --param_n_tiles_side "{{workflow.parameters.param_n_tiles_side}}"
            --param_max_x "{{workflow.parameters.param_max_x}}"
            --param_min_x "{{workflow.parameters.param_min_x}}"
            --id "1f7a48f";
    - name: splitter-3a67fba-tmp
      inputs:
        parameters:
        - name: laz_files_c31a712
      outputs:
        parameters:
          - name: splitter_target_3a67fba
            valueFrom:
              path: /tmp/splitter_target_3a67fba.json
      script:
        image: python:alpine3.9
        command: [python]
        source: |
          import json
          laz_files_c31a712 = {{inputs.parameters.laz_files_c31a712}}
          f_out = open("/tmp/splitter_target_3a67fba.json", "w")
          f_out.write(json.dumps(laz_files_c31a712))
          f_out.close()
    - name: fetch-tiles-19-04-22-a98d029-tmp
      outputs:
        parameters:
          - name: tiles_a08a42d
            valueFrom:
              path: /tmp/tiles_a08a42d.json
      container:
        image: "skoulouz/fetch-tiles-19-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python fetch-tiles-19-04-22.py
            --param_hostname "{{workflow.parameters.param_hostname}}"
            --param_login "{{workflow.parameters.param_login}}"
            --param_password "{{workflow.parameters.param_password}}"
            --id "a08a42d";
```
