### ISSUE TITLE
Add sample notebook to all users.

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#127]
Copy laserfarm notebook to all users

**Comment by skoulouzis** [comment]
Need to add config to helm:
```yaml
                  singleuser:
                    lifecycleHooks:
                      postStart:
                        exec:
                          command:
                            - "sh"
                            - "-c"
                            - >
                              mkdir -p /home/jovyan/examples && cp -r /tmp/notebooks/ /home/jovyan/examples/
```
