### ISSUE TITLE
workflow template saves image registry as test_image

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#248]
workflow template saves image registry as test_image:
```yaml
    - name: fetch-laz-files-01-06-22-792f561-tmp
      outputs:
        parameters:
          - name: laz_files_342086d
            valueFrom:
              path: /tmp/laz_files_342086d.json
      container:
        image: "test_image/fetch-laz-files-01-06-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python fetch-laz-files-01-06-22.py
            --param_password "{{workflow.parameters.param_password}}"
            --param_login "{{workflow.parameters.param_login}}"
            --param_hostname "{{workflow.parameters.param_hostname}}"
            --id "342086d";
```
