### ISSUE TITLE
exceeding data rate

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#340]
When I am trying to scrape some files (using BeautifulSoup) we are getting am ‘exceeding data rate’ error. The solution for this is to set a different limit when launching the docker image
```python
IOPub data rate exceeded.

The Jupyter server will temporarily stop sending output

to the client in order to avoid crashing it.

To change this limit, set the config variable

`--ServerApp.iopub_data_rate_limit`.

 

Current values:

ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)

ServerApp.rate_limit_window=3.0 (secs)
```

**Comment by skoulouzis** [comment]
We need to add in the values.yaml:
```yaml
                  singleuser:
                    extraFiles:
                      jupyter_notebook_config.json:
                        mountPath: /etc/jupyter/jupyter_notebook_config.json
                        data:
                          ServerApp:
                            iopub_data_rate_limit: 1.0e10
                            iopub_msg_rate_limitFloat: 3000
```
