### ISSUE TITLE
Building of cell as docker fails.

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#57]
https://github.com/QCDIS/NaaVRE-container-prestage/runs/4968452181?check_suite_focus=true 

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/installers/pip.py", line 70, in install
        return _pip_install_via_requirements(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/installers/pip.py", line 49, in _pip_install_via_requirements
        requirements.write('\n'.join(specs))
    TypeError: sequence item 0: expected str instance, NoneType found

**Comment by skoulouzis** [comment]
Looks like a badly formatted environment file:
```yaml
name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pdal
  - python-pdal
  - gdal
  - pip
  - pip:
    - 
```
