### ISSUE TITLE
Add 'volumeClaimTemplates' in template

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#838]
To be able to share a file system we simply declare a volumeClaimTemplates and then mount it on all tasks:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: n-a-a-vre-dev-user-name-at-domain-com-
  labels:
    vlab_slug: laserfarm
spec:
    entrypoint: n-a-a-vre-dev-user-name-at-domain-com
    volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
    - metadata:
        name: workdir                     # name of volume claim
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi                  # Gi => 1024 * 1024 * 1024
    arguments:
      parameters:
    templates:
    - name: n-a-a-vre-dev-user-name-at-domain-com
      dag:
        tasks:
        - name: loop-dev-user-name-at-domain-com-9cf5cb2
          dependencies: [ splitter-792ef18 ]
          template: loop-dev-user-name-at-domain-com-9cf5cb2-tmp
          arguments:
            parameters:
            - {name: splitter_target_792ef18, value: "{{item}}"}
          withParam: "{{tasks.splitter-792ef18.outputs.parameters.splitter_target_792ef18}}"
        - name: splitter-792ef18
          dependencies: [ message1-dev-user-name-at-domain-com-8140c5c ]
          template: splitter-792ef18-tmp
          arguments:
            parameters:
            - {name: msg_d5c3107, value: "{{tasks.message1-dev-user-name-at-domain-com-8140c5c.outputs.parameters.msg_d5c3107}}"}
        - name: print-message1-dev-user-name-at-domain-com-ee0e7a9
          dependencies: [ message1-dev-user-name-at-domain-com-8140c5c ]
          template: print-message1-dev-user-name-at-domain-com-ee0e7a9-tmp
          arguments:
            parameters:
            - {name: msg_d5c3107, value: "{{tasks.message1-dev-user-name-at-domain-com-8140c5c.outputs.parameters.msg_d5c3107}}"}
        - name: message1-dev-user-name-at-domain-com-8140c5c
          template: message1-dev-user-name-at-domain-com-8140c5c-tmp

    - name: loop-dev-user-name-at-domain-com-9cf5cb2-tmp
      inputs:
        parameters:
        - name: splitter_target_792ef18
      outputs:
        parameters:
      container:
        image: "qcdis/loop-dev-user-name-at-domain-com"
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python loop-dev-user-name-at-domain-com.py
            --msg {{inputs.parameters.splitter_target_792ef18}}
            --id  1f90ce4; find /mnt/vol; cat /mnt/vol/hello_world.txt;
        volumeMounts:                     # same syntax as k8s Pod spec
        - name: workdir
          mountPath: /mnt/vol
    - name: splitter-792ef18-tmp
      inputs:
        parameters:
        - name: msg_d5c3107
      outputs:
        parameters:
          - name: splitter_target_792ef18
            valueFrom:
              path: /tmp/splitter_target_792ef18.json
      script:
        image: python:alpine3.9
        command: [python]
        source: |
          import json
          msg_d5c3107 = {{inputs.parameters.msg_d5c3107}}
          list_of_lists = []
          for elem in msg_d5c3107:
            list = [elem]
            list_of_lists.append(list)
          f_out = open("/tmp/splitter_target_792ef18.json", "w")
          f_out.write(json.dumps(list_of_lists))
          f_out.close()
        volumeMounts:                     # same syntax as k8s Pod spec
        - name: workdir
          mountPath: /mnt/vol
    - name: print-message1-dev-user-name-at-domain-com-ee0e7a9-tmp
      inputs:
        parameters:
        - name: msg_d5c3107
      outputs:
        parameters:
      container:
        image: "qcdis/print-message1-dev-user-name-at-domain-com"
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python print-message1-dev-user-name-at-domain-com.py
            --msg {{inputs.parameters.msg_d5c3107}}
            --id  0fd753d; find /mnt/vol; cat /mnt/vol/hello_world.txt;
        volumeMounts:                     # same syntax as k8s Pod spec
        - name: workdir
          mountPath: /mnt/vol
    - name: message1-dev-user-name-at-domain-com-8140c5c-tmp
      outputs:
        parameters:
          - name: msg_d5c3107
            valueFrom:
              path: /tmp/msg_d5c3107.json
      container:
        image: "qcdis/message1-dev-user-name-at-domain-com"
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python message1-dev-user-name-at-domain-com.py
            --id  d5c3107; echo "Hello World"  | tee /mnt/vol/hello_world.txt;
        volumeMounts:                     # same syntax as k8s Pod spec
        - name: workdir
          mountPath: /mnt/vol
```
